### ISSUE TITLE
Misc. code style/cleanup issues

### ISSUE THREAD

**Issue by broofa** [autovance/ftp-srv#140]
My apologies for the unsolicited style advice, but there were a couple of jarring stylistic issues I noticed.  Do with these what you will...

- [ ] pasv_* options JS-style camelcase (pasvMin, pasvMax, pasvUrl
- [ ] add an `.eslintrc.json`, add `lint` script to `package.json`
- [ ] Avoid unnecessarily inconsistent naming.  (e.g. `FtpConnection` is implemented in `connection.js`, then required as `Connection` in index.js... makes it unnecessarily difficult to follow what's going on).  Some other candidates for improvement here...

```
const ActiveConnector = require('../../connector/active');
const BaseConnector = require('./connector/base');
const Commands = require('./commands');
const Connection = require('./connection');
const Connector = require('./base');
const DEFAULT_MESSAGE = require('./messages');
const FileSystem = require('./src/fs');
const PassiveConnector = require('../../connector/passive');
const REGISTRY = require('./registry');
const escapePath = require('../../helpers/escape-path');
const getFileStat = require('../../helpers/file-stat');
const resolveHost = require('./helpers/resolve-host');
const {getNextPortFactory} = require('./helpers/find-port');
````

**Comment by trs** [comment]
I appreciate this issue! It's a great outline to some styling issue I completely agree with.
Improving this isn't a huge priority for me at the moment, but are all good things to keep in mind for future projects and improvements down the road.

**Comment by forstermatth** [comment]
I'm going to close this, as this will be corrected when we implement the TypeScript version of this repository.
