### ISSUE TITLE
econnreset error upon testing with JMeter

### ISSUE THREAD

**Issue by tlonist-sang** [autovance/ftp-srv#163]
I was using JMeter to test if the server stands well against many concurrent requests from outside, then I kept on getting ECONNRESET error from the server which results in sudden stoppage. 

I googled and found out https://stackoverflow.com/questions/17245881/node-js-econnreset - the mentioned error is due to abrupt disconnection from the client side. I assume it is from the JMeter not caring the usual handshake process of FTP

I want to find a way to handle this error - to ignore this error, to be more specific - to test the stability of the server. Right now the error is captured in

ftpServer.on('client-error', ({ context, error }) => { 
  console.error(`FTP server error: error interfacing with client ${context} ${error} on ftp://${JSON.stringify(error)}`); 
}); 

and does not propagate further from here. 
I hope to know if there is a way to automatically reboot the server on sudden death, or to ignore the connection error from the client so that it can continue to download files from the server.

Thanks

**Comment by trs** [comment]
I’m not sure how to pin this issue down. It seems to me if the connection errors our, it’ll emit the `error` event (which is handled). I’m not sure what causes the server to stop working.

**Comment by forstermatth** [comment]
This can be reopened if it is still an issue, but we have released a few bug fixes aimed towards these types of errors recently.
