### ISSUE TITLE
TLS on Ftp-srv

### ISSUE THREAD

**Issue by tlonist-sang** [autovance/ftp-srv#170]
This is a question about setting up a TLS connection when creating a server with ftp-srv. I've read https://github.com/trs/ftp-srv/issues/45 regarding the TLS setup of ftp-srv, but I'm afraid I've got little help from it.

As far as I understand from ftp-srv document, I can configure a boolean variable TLS (true/false) when making ftpServer object (by using new FtpSrv({tls: ${value})}). But where do I configure my certificate and private key files in TLS? It should be configured in somewhere, but I can't find the right point to start. 

Also, if I want both ftp and ftps server be available at the same time, should I create two ftpServer objects? One with tls configuration and the other with none?

**Comment by Shinrai** [comment]
As noted here: https://github.com/trs/ftp-srv/blob/master/README.md#tls

You provide a TLS secure context object and not true/false.

Unfortunately unless I’m wrong looking at the code the server runs either TLS or not. Even though it would appear most of the code would support running NON TLS then upgrading to TLS. But it seems the isTLS() variable looks for ftps: in the url and the TLS context object to be set. 

I’d have to do some testing but based on the code I’d presume if it didn’t look for ftps: in the url you could run a non-TLS server with AUTH TLS support.

**Comment by Ferdinandkraft** [comment]
In addition to provide `cert`, `key` and `ca` in the `tls` object, you must also include the protocol `ftps://...` in the `url` parameter.

**Comment by trs** [comment]
Specifying `ftps` will make the server use implicit TLS. Meaning all connections have to be through TLS.
Without specifying `ftps` in the url, but still having a tls object set, will make the server use explicit TLS, meaning connections can be insecure, but can upgrade to a secure connection by sending the `AUTH TLS` command.
