### ISSUE TITLE
`greeting` Not `utf-8`?  garbled

### ISSUE THREAD

**Issue by d1y** [autovance/ftp-srv#180]
```js
// server.js
const server = new ftpsrv({
  greeting: "中文"
})

// client.js
client.on('greeting', msg=> {
  console.log(msg) //  è¿¥æ
  console.log(new Buffer(msg).toString()) // è¿¥æ
})
```

**Comment by trs** [comment]
The connection uses UTF-8 encoding _except_ if the client explicitly sends `UTF8 OFF`, in which case it uses ASCII.
Testing with filezilla, it correctly sees recieves: `Response: 	220-中文`

Is your client configured to use UTF-8 correctly?
