### ISSUE TITLE
Is there an event to detect `delete files`?

### ISSUE THREAD

**Issue by d1y** [autovance/ftp-srv#181]
```js
ftpServer.on('login', ({ connection })=> {
    // upload file event
    connection.on('STOR', (err, filename)=> {})
   //  download file event
    connection.on('RETR', ()=>{})
   //  renamed file
   connection.on('RNTO', ()=>{})
})
```

but,  Didn't delete the event handler?
Very confused about this problem, no relevant introduction found in the documentation
Do I need to implement it myself? Are there any friends to tell me how to solve this problem, thank you very much🌚

**Comment by d1y** [comment]
I seem to have found a solution,  Just need to customize `filesystem` to solve my needs

貌似找到解决办法了, 只需要自己继承一下 `filesystem` 改写即可

示例(Example)

```js
const {  FtpSrv, FileSystem } = require('ftp-srv')

class FS extends FileSystem {
  constructor(){
     super(...arguments)
  }
  currentDirectory() {
    console.log('现在的目录: ', this.cwd)
    super.currentDirectory()
  }
  delete(path) {
    console.log('删除的目录为: ', path)
    super.delete()
  }
}
```

https://gist.github.com/d1y/dffddd1ec1fe1a7b1a4505f105b7bb61

**Comment by trs** [comment]
Using the [`STOR` command as an example](https://github.com/trs/ftp-srv/blob/master/src/commands/registration/stor.js#L58), this could be added to the [`DELE` command handler](https://github.com/trs/ftp-srv/blob/master/src/commands/registration/dele.js#L10).

```js
.tap(() => this.emit('DELE', null, command.arg))
```

**Comment by PhaserEditor2D** [comment]
I think `DELE` is a very important command here for logging.
