### ISSUE TITLE
Basic FileSystem example?

### ISSUE THREAD

**Issue by skitsanos** [autovance/ftp-srv#182]
Hi, 

Is there any link that describes how FileSystem should be implemented? Let's say i wanna have some list of items sent on list() command ['inbox', 'sent', 'trash'] and will need to catch read/write for those 'locations'...

Thanks in advance.

**Comment by trs** [comment]
The [default file system](https://github.com/trs/ftp-srv/blob/master/src/fs.js) would have the methods that are used. It is based on the system's actually FS.
A new system can be implemented to support a "virtual" FS, or a specific system like you specify.

```js
class MyFileSystem {
  list() {
    return Promise.resolve(['inbox', 'sent', 'trash']);
  }
}
```

**Comment by ympondaven** [comment]
Hi, 
thanks for this sample, it's helpful ! 

I've tried that but I've this error : {"name":"ftp-srv","hostname":"xxxxxxx","pid":9486,"id":"a1607242-f59a-413c-ae2e-0041f8ecad71","directive":"LIST","level":50,"err":{"message":"fileStat.isDirectory is not a function","name":"TypeError","stack":"TypeError: fileStat.isDirectory is not a function\n    at Object.ls 

do you kown why ?

**Comment by ympondaven** [comment]
I found :) 
it's like that : 

    list (path) {
        console.log ('list');
        return Promise.resolve([
            {
                name: 'test1',
                dev: 2114,
                ino: 48064969,
                mode: 33188,
                nlink: 1,
                uid: 85,
                gid: 100,
                rdev: 0,
                size: 527,
                blksize: 4096,
                blocks: 8,
                atime: 'Mon, 10 Oct 2011 23:24:11 GMT',
                mtime: 'Mon, 10 Oct 2011 23:24:11 GMT',
                ctime: 'Mon, 10 Oct 2011 23:24:11 GMT',
                birthtime: 'Mon, 10 Oct 2011 23:24:11 GMT',
                isDirectory: () => false
              }, {
                name: 'test2',
                dev: 2114,
                ino: 48064969,
                mode: 33188,
                nlink: 1,
                uid: 85,
                gid: 100,
                rdev: 0,
                size: 527,
                blksize: 4096,
                blocks: 8,
                atime: 'Mon, 10 Oct 2011 23:24:11 GMT',
                mtime: 'Mon, 10 Oct 2011 23:24:11 GMT',
                ctime: 'Mon, 10 Oct 2011 23:24:11 GMT',
                birthtime: 'Mon, 10 Oct 2011 23:24:11 GMT',
                isDirectory: () => true
              }
        ]);
            
        }
