### ISSUE TITLE
Logging in module FtpContext.js

### ISSUE THREAD

**Issue by JonathanRowell** [autovance/ftp-srv#188]
In this module there is a variable "verbose" which is set to false and if you set it to true it logs to the console. It ought to log to the log given on construction (default bunyan log) and depend on the log level.

In particular logging the commands coming over the wire at code line 266 would be extremely useful since a non whitelisted command gives an error "502 Command not whitelisted" without saying what command it is!

**Comment by trs** [comment]
All logs are done through the `log` from the constructor.

Adding the command to this error is a great addition: https://github.com/autovance/ftp-srv/pull/208/commits/fdf5c49daa19a2231426270d83f197c0236d3dea
