### ISSUE TITLE
size limit for each user

### ISSUE THREAD

**Issue by RezaErfani67** [autovance/ftp-srv#196]
how can i set size limit for each user?
for example each user can upload 20 Gigabyte

**Comment by Squarix** [comment]
I just made my custom FileSystem
On write its sending request on db and getting size left per user
Then I use transform stream to count bytes on writeStream

`class myTransformer extends Transform {
  constructor(maxSize = 0, sizeData = {}) {
    super();
    this.maxSize = maxSize;
    this.sizeData = sizeData
    this.currentSize = 0;
  }
  _transform(data, encoding, cb) {
    this.currentSize += data.length;

    if (this.maxSize && this.currentSize > this.maxSize) {
      this.emit('end');
    } else {
      cb(null, data, encoding);
    }
  }

  _flush(cb) {
    this.sizeData.size = this.currentSize;
    cb();
  }
}`

Write override: 
`async write(fileName, {append, start}) {
    const writableStream = super.write(fileName, { append, start });

    const { limit } = await getLimit(this.accessToken);
    const transformStream = new myTransformer(limit, this.sizeData);

    const stream = writableStream.stream;
    transformStream.pipe(stream);
    writableStream.stream = transformStream;

    return writableStream;
  }`

Also I edit user limits on upload event and on delete
`connection.on('STOR', async (err, path) => {
    let { accessToken } = auth;
    if (err) {
      console.log('Error: ', err);
    } else {
      console.log(accessToken);
      await putFile(accessToken, `${auth.user.id}/${path}`, sizeData.size).catch(e => console.log('Error: ', e))
    }
  });`
