### ISSUE TITLE
Root directory 

### ISSUE THREAD

**Issue by ympondaven** [autovance/ftp-srv#202]
Hello, I've tried this : 
```js
resolve({
  root: require('os').homedir(),
  "cwd": cwd,
  "fs": new MyFileSystem(connection, {
    root: require('os').homedir(),
    cwd: cwd
  })
});
```
and root = "/tmp" ... but still using the project directory. 

constructor for myfilesystem : 
```js
constructor(connection, {root, cwd} = {}) {
  console.log ("root fs " + root);
  super(connection, root, cwd);
}
```
What's wrong ? 

Regards,

**Comment by trs** [comment]
Your `super` call is incorrect in your custom file system constructor.

The second argument is an [object](https://github.com/autovance/ftp-srv/blob/0b9167e1e44f41306925879a234f3d914a8b13f7/src/fs.js#L10).

```diff
constructor(connection, {root, cwd} = {}) {
  console.log ("root fs " + root);
-  super(connection, root, cwd);
+  super(connection, {root, cwd});
}
```
