### ISSUE TITLE
SFTP support?

### ISSUE THREAD

**Issue by ajmas** [autovance/ftp-srv#204]
Does this project provide support for SFTP? Guessing since it is not specifically stated it is probably a no, but thought I'd check anyhow.

**Comment by trs** [comment]
Doesn't hurt to ask! But no, unfortunately this project does not support SFTP. Might be something to consider in the future though.

**Comment by MickL** [comment]
I would also like to let my user authenticate by using a private key while the ftp server holds the public key. Can this issue be reopened?

**Comment by matt-forster** [comment]
We are certainly open to contributions on this front!
