### ISSUE TITLE
test file start.js not actually testing TLS connection

### ISSUE THREAD

**Issue by Ferdinandkraft** [autovance/ftp-srv#209]
File [start.js](https://github.com/autovance/ftp-srv/blob/master/test/start.js#L7) is missing the `ftps` protocol in the `url` parameter, despite populating the `tls` object in line 11. A plain FTP server is started instead.

**Comment by trs** [comment]
This example is using an explicit connection, the connection can be upgraded with `AUTH TLS`. See my other comment here: https://github.com/autovance/ftp-srv/issues/170#issuecomment-663883739
