### ISSUE TITLE
How to use connection object to see command like RETR etc

### ISSUE THREAD

**Issue by MotagamwalaTaha** [autovance/ftp-srv#219]
# RETR

```
connection.on('RETR', (error, filePath) => { ... }); // this doesn`t works and return error
```
Occurs when a file is downloaded.

 error if successful, will be null
filePath location to which file was downloaded

connection.on does not exists until the connection is made then how to implement them help

**Comment by MotagamwalaTaha** [comment]
> 
> # RETR
> 
> ```
> connection.on('RETR', (error, filePath) => { ... }); // this doesn`t works and return error
> ```
> 
> Occurs when a file is downloaded.
> 
> error if successful, will be null
> filePath location to which file was downloaded
> 
> connection.on does not exists until the connection is made then how to implement them help

Full example on how to use this will be helpfull

**Comment by trs** [comment]
The `login` even takes a `connection` in the second argument, so you can hook into events there.

```js
const {FtpSrv} = require('ftp-srv');

const ftpServer = new FtpSrv({ ... });

ftpServer.on('login', ({connection, username, password}, resolve, reject) => {
  if (!yourAuthMethod(username, password)) return reject(new Error('Bad login'));

  connection.on('RETR', (err, path) => {
    console.log('retr' path, err);
  });

  resolve();
});
```

----

If you have implemented a custom file system, you could also handle events in the constructor.

```js
const {FtpSrv, FileSystem} = require('ftp-srv');

class MyFileSystem extends FileSystem {
  constructor(connection, args) {
    super(connection, args);

    connection.on('RETR', (error, filePath) => { ... });
  }
}
```

**Comment by MotagamwalaTaha** [comment]
Thanks for the answer
