### ISSUE TITLE
In-memory stor

### ISSUE THREAD

**Issue by masterit-technologies** [autovance/ftp-srv#239]
Hi everyone, Is it possible to use ftp-srv just for stream redirecting?

I need to catch event STOR and save data into my database, not write on hdd.

Maybe it is stupide question but I dont have any experiences with it.

If its possible can you provide me some short example how to do that?
Thanks.

**Comment by forstermatth** [comment]
The best place for this would be the discussions section! 

https://github.com/autovance/ftp-srv/discussions
