### ISSUE TITLE
Control user permissions while login (--read-only)

### ISSUE THREAD

**Issue by Azamatjon** [autovance/ftp-srv#244]
Can you add a feature to control users while using ftp, like I want to give only-read permissions for some users.

**Comment by matt-forster** [comment]
You are free to implement your own access control strategies - include read-only for some users - through the file system and login events. You could blacklist the write FTP commands for the connections if the user meets your requirements.

https://github.com/autovance/ftp-srv#login

**Comment by trs** [comment]
The [cli also does provider a `--read-only` argument](https://github.com/autovance/ftp-srv#--read-only).
If you require that outside of the cli then you can do what matt-forster stated. Check out the [cli code for a list of the write commands](https://github.com/autovance/ftp-srv/blob/master/bin/index.js#L105-L107).
