### ISSUE TITLE
[Feature request] Support silent mode

### ISSUE THREAD

**Issue by icetee** [autovance/ftp-srv#47]
If I started listening server always show log in command line. That would not be a problem. But if I use part of a system then it is a problem! If I set the log option to `null` or `false`, I get error.

I would like to have a 'slient' option.

**Comment by trs** [comment]
If you initialize a new [bunyan](https://github.com/trentm/node-bunyan#levels) instance, you can set the level to `fatal` and it won't output any errors since fatal is never used.

```js
const quietLog = bunyan.createLogger({
  name: 'quiet-logger',
  level: 60
});

const ftp = new FtpServer({
  log: quietLog
  ...
});
```
