### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by blechatellier** [autovance/ftp-srv#63]
I'm trying to upload multiple images at once but only the first one is going through, all parallel requests throw a `530 Command requires authentication`.

It works if I comment out this condition: https://github.com/trs/ftp-srv/blob/master/src/commands/index.js#L56

When uploading a single file I get:
```
// (command.directive, commandFlags.no_auth, this.connection.authenticated)
USER true undefined
PASS true undefined
TYPE undefined true
PASV undefined true
STOR undefined true
```

When uploading two files I get:
```
// (command.directive, commandFlags.no_auth, this.connection.authenticated)
USER true undefined
PASV undefined undefined
PASS true undefined
STOR undefined true
TYPE undefined true
PASV undefined true
STOR undefined true
```

I guess `PASV undefined undefined` is throwing the `530`. Should the `PASV` command have a `no_auth: true`?

**Comment by trs** [comment]
Are you uploading these files using new connections each time? If so, all new connections need to be authenticated.

**Comment by pastawoua** [comment]
Thanks @trs - it works if I create one instance per upload. If I use any FTP software (ie: CyberDuck) and try to drag multiple files to upload, it will fail though. Not sure how those clients handle multiple file uploads.

**Comment by trs** [comment]
Interesting, I'll take a look into that. Thanks for the heads up.

**Comment by pastawoua** [comment]
Is there any throttling in `net_class_net_server`? Looks like if I try to drop 6 files at once, only 5 will randomly get through.

**Comment by trs** [comment]
Not that I'm aware of.

Testing this with FileZilla works just fine. I'll have to try out CyberDuck.

**Comment by pastawoua** [comment]
Just tried with FileZilla and it worked 👍

**Comment by trs** [comment]
Are you using explicit AUTH TLS?

**Comment by pastawoua** [comment]
No I'm not, not sure what CyberDuck is doing differently.

**Comment by pastawoua** [comment]
Looking at FileZilla logs, I also get some errors when trying to upload multiple files at once:
`Error: The data connection could not be established: ECONNREFUSED - Connection refused by server`

Looks like FileZilla is smart enough to retry a failed upload though, CyberDuck isn't.

**Comment by trs** [comment]
I can't seem to recreate that connection error in FileZilla. 😕 

---- 

Cyberduck seems to *ignore* the `150` response from `LIST` and acts like each following response is for the next command sent. This makes the responses being processed by Cyberduck out of order, even though the server sends them in the correct order.

![image](https://user-images.githubusercontent.com/15315657/34347351-6754ed5a-e9bf-11e7-93e3-91e9bbbdf250.png)

![image](https://user-images.githubusercontent.com/15315657/34347358-7abccc14-e9bf-11e7-8cb2-4db2c9eb1c85.png)

**Comment by erickpece** [comment]
I'm having this happen happen as well with Transmit 5.2.1.  Glad to help test!

**Comment by trs** [comment]
@erickpece Thanks for the heads up!
Can you post your `ftp-srv` config?

**Comment by erickpece** [comment]
After more digging, looks like this may be a different issue.

When using PASV mode for multiple file transfers, I'm getting this error:

```
/Users/erick/Desktop/ftpsrv-bug/node_modules/ftp-srv/src/helpers/find-port.js:34
      const {port} = portCheckServer.address();
             ^

TypeError: Cannot destructure property `port` of 'undefined' or 'null'.
```

Here's my current config:

```js
const FtpSrv = require('ftp-srv');
const ftpServer = new FtpSrv({
  url: 'ftp://0.0.0.0:2121',
  pasv_url: 'ftp://192.168.1.203:2121'
});

ftpServer.on('login', (data, resolve, reject) => {
  resolve({
    root: 'files'
  });
});

ftpServer.listen();
```

If I modify find-port so that the result of `portCheckServer.address()` is checked for null first, it seems to work:

```js
let address = portCheckServer.address();

if (address !== null) {
  const {port} = portCheckServer.address();
  portCheckServer.close(() => resolve(port));
} else {
  portCheckServer.close(() => resolve());
}
```

I'm not sure this is the right fix though.

**Comment by erickpece** [comment]
I think my pasv_url is wrong too.  Stopped getting another error after changing it to `192,168,1,203`
